
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: dynamodb
          content-type: application/json
cloud:
  aws:
    credentials:
      accesskey: ${AWS_ACCESS_KEY}
      secretkey: ${AWS_SECRET_KEY}
      profile-name: ${AWS_PROFILE}
    region:
      static: us-west-2
    stack:
      auto: false
logging:
  level:
    io.nbugash.titan: DEBUG
server:
  port: 8080
