
spring:
  main:
    web-application-type: none
  cloud:
    stream:
      kinesis:
        bindings:
          input:
            consumer:
              shardIteratorType: LATEST
      bindings:
        input:
          destination: redshift
          content-type: text/plain
cloud:
  aws:
    s3:
      bucket:
        name: titan-s3-bucket
    credentials:
      accesskey: ${AWS_ACCESS_KEY}
      secretkey: ${AWS_SECRET_KEY}
      profile-name: ${AWS_PROFILE}
    region:
      static: us-west-2
    stack:
      auto: false
logging:
  level:
    io.nbugash.titan: DEBUG
